name: active-room-seg
channels:
  - aihabitat
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - habitat-sim=0.2.4
  - numpy=1.26.4
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - gym==0.26.2
      - imageio==2.37.0
      - matplotlib==3.9.4
      - numba==0.60.0
      - numpy-quaternion==2023.0.4
      - opencv-python==4.11.0.86
      - Pillow==9.5.0
      - PyYAML==6.0.3
      - scikit-fmm==2025.1.29
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - torch==2.7.1+cu128
      - torchvision==0.22.1+cu128
      - python-igraph==0.11.9
      - seaborn==0.13.2
      - tqdm==4.67.1
      - treelib==1.7.1
      - yacs==0.1.8
